services:
  redis:
    image: redis:6
    ports:
      - '6379:6379'

  celery:
    build: .
    command: celery -A tasks worker -P gevent -c 50 -l info
    depends_on:
      - redis

  app:
    build: .
    depends_on:
      - redis
      - celery
    command: python main.py
